# Generated by Django 5.0.7 on 2024-07-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
